add the mlp model for alpa
silencelamb/alpa pull request #3
Opened 2023-06-15 03:17 UTC by haichaozhang

2023-06-15 05:05 UTC, silencelamb commented on benchmark/alpa/suite_auto_gpt.py
> +    4: get_search_cases(mlp_spacs["4layers"], [128], [1]),
别在这里改啊。。另外加一个suite

2023-06-15 05:07 UTC, silencelamb commented on alpa/pipeline_parallel/stage_construction.py
> +    gap = 1e-12
这个为什么要改啊？

2023-06-15 05:08 UTC, silencelamb commented on benchmark/alpa/suite_auto_gpt.py
> +    4: get_config_cases(mlp_spacs["4layers"], [128],
specs

2023-06-15 05:11 UTC, silencelamb commented on benchmark/alpa/suite_auto_gpt.py
> +    8: get_config_cases(mlp_spacs["4layers"], [128],
MLP的别和gpt混着写在一起；
单独建立一个sutai_auto_mlp.py

2023-06-15 05:11 UTC, silencelamb requested changes
见评论

2023-06-16 03:22 UTC, haichaozhang commented on alpa/pipeline_parallel/stage_construction.py
> +    gap = 1e-12
因为MLP较小，gap设置大了，会没有solution，已经针对MLP进行了更改，提交了最近的commit [update mlp model for alpa]

2023-06-16 03:22 UTC, haichaozhang commented on benchmark/alpa/suite_auto_gpt.py
> +    4: get_search_cases(mlp_spacs["4layers"], [128], [1]),
已经修改了，提交了最近的commit [update mlp model for alpa]

2023-06-16 03:22 UTC, haichaozhang commented on benchmark/alpa/suite_auto_gpt.py
> +    4: get_config_cases(mlp_spacs["4layers"], [128],
提交了最近的commit [update mlp model for alpa]

2023-06-16 03:23 UTC, haichaozhang commented on benchmark/alpa/suite_auto_gpt.py
> +    8: get_config_cases(mlp_spacs["4layers"], [128],
已经修改，并且提交了最近的commit [update mlp model for alpa]

2023-06-16 04:40 UTC, silencelamb approved these changes

2023-06-16 05:33 UTC, merged